### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by Simoncl** [NVIDIA/jitify#16] opened 2018-09-17 02:48 UTC
Hi.
I''m currently getting these errors when running the simple example
--- JIT compile log for my_program ---
---------------------------------------------------
type_traits(18): error: expected an identifier

type_traits(19): error: expected a ")"

type_traits(19): error: a template argument list is not allowed in a declaration of a primary template

3 errors detected in the compilation of "my_program".

Any thoughts?

**Comment by Simoncl** [comment] 2018-09-17 03:10
If I remove the #include <type_traits> from jitsafe_header_preinclude_h I then get the following
error looks like the name is being generated incorrectly  
__nv_name_map(2): error: Error in parsing name expression for lowered name lookup. Input name expression was: " my_kernel < ( nt * __ptr64 ) 3, loat * __ptr64 >"
I think it should be 
 my_kernel < ( int * __ptr64 ) 3, float * __ptr64 >"

**Comment by benbarsdell** [comment] 2018-09-17 04:17
Thanks for the report.

It appears the second error is caused by MSVC having different behavior for typeid(T).name() compared to gcc/clang. E.g., where gcc/clang give this:
```
i
Pi
f
Pf
3FooIdE
P3FooIdE
```
MSVC gives this:
```
int
int * __ptr64
float
float * __ptr64
struct Foo<double>
struct Foo<double> * __ptr64
```

We will have to work around this issue. Does it still break if you remove the `+ 1` from this line? https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L699

**Comment by Simoncl** [comment] 2018-09-17 19:15
Hi.
Thanks for getting back. Removing the  +1 seems to have fixed the names but I get the following error

--- JIT compile log for my_program ---
---------------------------------------------------
__nv_name_map(2): error: expected a ")"

__nv_name_map(2): error: non-integral operation not allowed in nontype template argument

__nv_name_map(2): error: Error in parsing name expression for lowered name lookup. Input name expression was: " my_kernel < ( int * __ptr64 ) 3, float * __ptr64 >"

3 errors detected in the compilation of "my_program".

**Comment by Simoncl** [comment] 2018-09-19 04:49
Hi.
Just looking at getting jitify going I have a few questions. 
In the simple example you call program.kernel("my_kernel").instantiate(3, type_of(*d_data))
I get the following error .
jitify::Kernel::instantiate': function does not take 2 arguments

Are the examples out of date?

**Comment by Simoncl** [comment] 2018-09-19 05:05
In the simple example provided you pass float as the template type 
The program launch command it expects  std::vector<void*> arg_ptrs = std::vector<void*>(), as the first arg
how does this compile if your passing *float.
I get the following error.
cannot convert argument 1 from 'T *' to 'std::vector<void *,std::allocator<_Ty>>
Apologies if I'm doing something wrong. I'm just trying to get the examples to build with msvc

**Comment by benbarsdell** [comment] 2018-09-19 05:08
Are you building with C++11? There are variadic overloads of those methods: https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L1951

**Comment by Simoncl** [comment] 2018-09-19 05:11
Yeah I'm using C++ 14

**Comment by Simoncl** [comment] 2018-09-19 05:14
Sorry just checked visual studio still reports this 199711 when using  __cplusplus

**Comment by Simoncl** [comment] 2018-09-19 05:31
I can manually use a compiler switch to set this macro Zc:__cplusplus 
I can build the default simple example again with the modified .hpp removing the +1 and I get the same errors

__nv_name_map(2): error: expected a ")"

__nv_name_map(2): error: non-integral operation not allowed in nontype template argument

__nv_name_map(2): error: Error in parsing name expression for lowered name lookup. Input name expression was: " my_kernel < ( int * __ptr64 ) 3, float * __ptr64 >"

**Comment by Simoncl** [comment] 2018-09-19 05:32
I appreciate any help.

**Comment by benbarsdell** [comment] 2018-09-19 05:36
I think "__ptr64" needs to be removed from the string (at the same part of the code where that +1 is).

I'll have a go at fixing these issues tomorrow.

**Comment by Simoncl** [comment] 2018-09-19 05:39
Ok great. I'm excited to use the project looks awesome!

**Comment by benbarsdell** [comment] 2018-09-19 19:45
Let me know if #17 allows you to get any further.

**Comment by Simoncl** [comment] 2018-09-19 22:16
Hi.
Looks like this is  working!  
bool test_simple_result = test_simple<float>();
I have to change these two lines for Windows
token = ::strtok_r(c_str, delims.c_str(), &saveptr);
to
token = ::strtok_s(c_str, delims.c_str(), &saveptr);

and
char* token;
to
char* token=NULL;

Thanks so much for looking into these issues and getting it working

**Comment by Simoncl** [comment] 2018-09-19 22:19
sorry that should have been 

bool test_simple_result = test_simple<float>() is working:)

**Comment by benbarsdell** [comment] 2018-09-19 22:45
Great! I've pushed another commit to the PR to fix those two issues.

**Comment by Simoncl** [comment] 2018-09-19 22:51
Quick question how do I generate this file my_header1.cuh.jit 
There is an include in the example.cpp but this file is not supplied in the repo
#include "example_headers/my_header1.cuh.jit"

Also moving on to the next test bool test_kernels_result = test_kernels< float >();
I get the following error
jitify.hpp(823): error C3861: 'demangle': identifier not found

**Comment by benbarsdell** [comment] 2018-09-19 23:41
The .jit file is generated with the provided "stringify" tool.

The demangling is actually more problematic than I thought, so I'll need to think about it a bit more. In the mean time, as a hack, you could try removing that broken line of code and just return an empty string from the function.

**Comment by benbarsdell** [comment] 2018-09-20 03:37
I've pushed a fix for the `'demangle': identifier not found` error to the PR.

Also the way to build and use the stringify tool can be seen here:
https://github.com/NVIDIA/jitify/blob/master/Makefile#L39-L43

**Comment by Simoncl** [comment] 2018-09-20 19:48
Hi.
Thanks the demangle seems to be passing now.
One question this file is referenced in the examples my_header4.cuh but not present in the repo?

**Comment by benbarsdell** [comment] 2018-09-20 21:20
That is part of a demonstration of the file callback feature:
https://github.com/NVIDIA/jitify/blob/master/jitify_example.cpp#L65
The file doesn't really exist, the callback just intercepts the request for it and returns a string containing the code.

**Comment by Simoncl** [comment] 2018-09-20 22:16
Oh OK.
I have almost the tests running. Thanks for looking at the issues.  It's very  exciting to be able to use the project.
Thanks again

**Comment by maddyscientist** [comment] 2018-09-24 16:56
Pull #17 closes this issue.  @Simoncl if you have any more issues, feel free to reopen this or open a new issue as applicable.

**Closed by maddyscientist** 2018-09-24 16:56 UTC
Labels: bug
